name: Horario de Operacion Sistema Render

on:
  schedule:
    # ENCENDER: Lunes a Sábado a las 7:30 AM (Hora CDMX). 
    # En UTC son las 13:30 horas. (Adelantado para ganarle a la fila de GitHub)
    - cron: '30 13 * * 1-6'
    
    # APAGAR: Lunes a Sábado a las 6:15 PM (Hora CDMX).
    # En UTC son las 00:15 horas del DÍA SIGUIENTE.
    # Se ejecuta de Martes(2) a Domingo(0).
    - cron: '15 0 * * 0,2-6'
    
  # Botón manual de emergencia
  workflow_dispatch:
    inputs:
      accion:
        description: 'Accion manual a realizar'
        required: true
        default: 'resume'
        type: choice
        options:
          - resume
          - suspend

jobs:
  gestionar_servidor:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar Acción en la API de Render
        run: |
          # Por defecto es encender
          ACCION="resume"
          
          # Guardamos las variables de GitHub de forma segura
          CRON_ACTUAL="${{ github.event.schedule }}"
          ACCION_MANUAL="${{ github.event.inputs.accion }}"
          
          # Comprobación flexible: Si el cron contiene "15 0" (la hora de apagar) o si elegiste suspender
          if [[ "$CRON_ACTUAL" == *"15 0"* ]] || [[ "$ACCION_MANUAL" == "suspend" ]]; then
            ACCION="suspend"
          fi
          
          echo "Hora Cron detectada por GitHub: '$CRON_ACTUAL'"
          echo "Acción seleccionada: ENVIANDO ORDEN DE $ACCION"
          
          # Añadimos parámetros para ver la respuesta exacta de Render y detectar errores
          curl -s -w "\n[Codigo HTTP de Render: %{http_code}]\n" -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/$ACCION" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"