name: Horario de Operacion Sistema Render

on:
  schedule:
    # ENCENDER: Lunes a Sábado a las 8:15 AM (Hora CDMX). 
    # En UTC son las 14:15 horas.
    - cron: '15 14 * * 1-6'
    
    # APAGAR: Lunes a Sábado a las 6:15 PM (Hora CDMX).
    # En UTC son las 00:15 horas del DÍA SIGUIENTE.
    # Se ejecuta de Martes(2) a Domingo(0).
    - cron: '15 0 * * 0,2-6'
    
  # Botón manual de emergencia
  workflow_dispatch:
    inputs:
      accion:
        description: 'Accion manual a realizar'
        required: true
        default: 'resume'
        type: choice
        options:
          - resume
          - suspend

jobs:
  gestionar_servidor:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar Acción en la API de Render
        run: |
          # Por defecto es encender
          ACCION="resume"
          
          # Si el reloj detecta que son las 00:15 UTC (6:15 PM México) o si seleccionaste suspender manual:
          if [ "${{ github.event.schedule }}" == "15 0 * * 0,2-6" ] || [ "${{ github.event.inputs.accion }}" == "suspend" ]; then
            ACCION="suspend"
          fi
          
          echo "Ejecutando orden de: $ACCION para el servidor..."
          
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/$ACCION" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"